<?php

use App\Models\ContactChannel;
use App\Models\CountdownSetting;
use App\Models\FrequentlyAskedQuestion;
use App\Models\GalleryMoment;
use App\Models\History;
use App\Models\LandingBodyElement;
use App\Models\LandingHeroImage;
use App\Models\LandingSetting;
use App\Models\LineupArtist;
use App\Models\MerchandiseProduct;
use App\Models\MerchandiseProductCategory;
use App\Models\MerchandiseProductImage;
use App\Models\NotFoundImage;
use App\Models\SeoSetting;
use App\Models\SpotifyPlaylist;
use App\Models\SponsorPartner;
use App\Models\Ticket;
use App\Models\TicketCardElement;

return [
    'seo-setting' => [
        'label' => 'SEO Settings',
        'navigation_label' => 'SEO',
        'navigation_group' => 'Website',
        'navigation_icon' => 'magnifying-glass',
        'model' => SeoSetting::class,
        'page_title' => 'SEO Settings',
        'description' => 'Kelola meta title, description, canonical URL, robots, Open Graph, Twitter Card, verification tag, dan structured data untuk landing page.',
        'single_record' => true,
        'searchable' => ['site_name', 'meta_title', 'meta_description', 'meta_keywords'],
        'with' => [],
        'default_sort' => [
            ['column' => 'id', 'direction' => 'desc'],
        ],
        'table_columns' => [
            ['key' => 'site_name', 'label' => 'Site Name'],
            ['key' => 'meta_title', 'label' => 'Meta Title', 'truncate' => 45],
            ['key' => 'meta_description', 'label' => 'Description', 'truncate' => 70],
            ['key' => 'og_image_path', 'label' => 'OG Image', 'type' => 'image'],
            ['key' => 'is_active', 'label' => 'Active', 'type' => 'boolean'],
        ],
        'form_fields' => [
            ['name' => 'site_name', 'label' => 'Site Name', 'type' => 'text', 'required' => true, 'default' => 'Purnama Bersantai'],
            ['name' => 'meta_title', 'label' => 'Meta Title', 'type' => 'text', 'required' => true, 'default' => 'Purnama Bersantai - Festival Musik Malam'],
            ['name' => 'meta_description', 'label' => 'Meta Description', 'type' => 'textarea', 'full_width' => true],
            ['name' => 'meta_keywords', 'label' => 'Meta Keywords', 'type' => 'textarea', 'full_width' => true],
            ['name' => 'canonical_url', 'label' => 'Canonical URL', 'type' => 'url'],
            ['name' => 'robots_index', 'label' => 'Allow Search Engines to Index', 'type' => 'checkbox', 'default' => true, 'full_width' => true],
            ['name' => 'robots_follow', 'label' => 'Allow Search Engines to Follow Links', 'type' => 'checkbox', 'default' => true, 'full_width' => true],
            ['name' => 'og_title', 'label' => 'Open Graph Title', 'type' => 'text'],
            ['name' => 'og_description', 'label' => 'Open Graph Description', 'type' => 'textarea', 'full_width' => true],
            ['name' => 'og_image_path', 'label' => 'Open Graph Image', 'type' => 'image'],
            ['name' => 'og_type', 'label' => 'Open Graph Type', 'type' => 'select', 'required' => true, 'default' => 'website', 'options' => [
                ['value' => 'website', 'label' => 'Website'],
                ['value' => 'article', 'label' => 'Article'],
                ['value' => 'event', 'label' => 'Event'],
            ]],
            ['name' => 'twitter_card', 'label' => 'Twitter Card Type', 'type' => 'select', 'required' => true, 'default' => 'summary_large_image', 'options' => [
                ['value' => 'summary_large_image', 'label' => 'Summary Large Image'],
                ['value' => 'summary', 'label' => 'Summary'],
            ]],
            ['name' => 'twitter_title', 'label' => 'Twitter Title', 'type' => 'text'],
            ['name' => 'twitter_description', 'label' => 'Twitter Description', 'type' => 'textarea', 'full_width' => true],
            ['name' => 'twitter_image_path', 'label' => 'Twitter Image', 'type' => 'image'],
            ['name' => 'theme_color', 'label' => 'Theme Color', 'type' => 'text', 'default' => '#151515'],
            ['name' => 'locale', 'label' => 'Locale', 'type' => 'text', 'default' => 'id_ID'],
            ['name' => 'google_site_verification', 'label' => 'Google Site Verification', 'type' => 'text'],
            ['name' => 'bing_site_verification', 'label' => 'Bing Site Verification', 'type' => 'text'],
            ['name' => 'schema_json', 'label' => 'Structured Data JSON-LD', 'type' => 'json', 'full_width' => true, 'hidden_from_form' => true],
            ['name' => 'is_active', 'label' => 'Active', 'type' => 'checkbox', 'default' => true, 'full_width' => true],
        ],
    ],
    'landing-setting' => [
        'label' => 'Landing Settings',
        'navigation_label' => 'Landing Settings',
        'navigation_group' => 'Landing Content',
        'navigation_icon' => 'adjustments-horizontal',
        'model' => LandingSetting::class,
        'page_title' => 'Landing Settings',
        'description' => 'Kelola identitas website, hero copy, footer, sponsor text, dan event info utama.',
        'single_record' => true,
        'searchable' => ['site_name', 'page_title', 'hero_tagline'],
        'with' => [],
        'default_sort' => [
            ['column' => 'id', 'direction' => 'desc'],
        ],
        'table_columns' => [
            ['key' => 'site_name', 'label' => 'Site Name'],
            ['key' => 'page_title', 'label' => 'Page Title'],
            ['key' => 'logo_path', 'label' => 'Logo', 'type' => 'image'],
            ['key' => 'hero_tagline', 'label' => 'Hero Tagline', 'truncate' => 50],
            ['key' => 'is_active', 'label' => 'Active', 'type' => 'boolean'],
        ],
        'form_fields' => [
            ['name' => 'site_name', 'label' => 'Site Name', 'type' => 'text', 'required' => true, 'default' => 'Purnama Bersantai'],
            ['name' => 'page_title', 'label' => 'Page Title', 'type' => 'text', 'required' => true, 'default' => 'Purnama Bersantai'],
            ['name' => 'hero_tagline', 'label' => 'Hero Tagline', 'type' => 'text'],
            ['name' => 'video_url', 'label' => 'Video URL', 'type' => 'url'],
            ['name' => 'hero_description', 'label' => 'Hero Description', 'type' => 'textarea', 'full_width' => true],
            ['name' => 'logo_path', 'label' => 'Logo', 'type' => 'image'],
            ['name' => 'hero_brand_path', 'label' => 'Hero Brand', 'type' => 'image'],
            ['name' => 'footer_description', 'label' => 'Footer Description', 'type' => 'textarea', 'full_width' => true],
            ['name' => 'sponsor_text', 'label' => 'Sponsor Text', 'type' => 'textarea', 'full_width' => true],
            ['name' => 'event_info', 'label' => 'Event Info JSON', 'type' => 'json', 'full_width' => true],
            ['name' => 'is_active', 'label' => 'Active', 'type' => 'checkbox', 'default' => true, 'full_width' => true],
        ],
    ],
    'countdown-setting' => [
        'label' => 'Countdown',
        'navigation_label' => 'Countdown',
        'navigation_group' => 'Landing Content',
        'navigation_icon' => 'clock',
        'model' => CountdownSetting::class,
        'page_title' => 'Countdown',
        'description' => 'Kelola target waktu countdown yang tampil di bawah logo hero landing page.',
        'single_record' => true,
        'searchable' => ['title', 'description'],
        'with' => [],
        'default_sort' => [
            ['column' => 'id', 'direction' => 'desc'],
        ],
        'table_columns' => [
            ['key' => 'title', 'label' => 'Title'],
            ['key' => 'target_at', 'label' => 'Target', 'type' => 'datetime'],
            ['key' => 'description', 'label' => 'Description', 'truncate' => 60],
            ['key' => 'is_active', 'label' => 'Active', 'type' => 'boolean'],
        ],
        'form_fields' => [
            ['name' => 'title', 'label' => 'Title', 'type' => 'text', 'required' => true, 'default' => 'PURNAMA BERSANTAI 2026'],
            ['name' => 'target_at', 'label' => 'Target Date & Time', 'type' => 'datetime', 'required' => true],
            ['name' => 'description', 'label' => 'Description', 'type' => 'textarea', 'full_width' => true],
            ['name' => 'is_active', 'label' => 'Active', 'type' => 'checkbox', 'default' => true, 'full_width' => true],
        ],
    ],
    'hero-image' => [
        'label' => 'Hero Images',
        'navigation_label' => 'Hero Images',
        'navigation_group' => 'Landing Content',
        'navigation_icon' => 'photo',
        'model' => LandingHeroImage::class,
        'page_title' => 'Hero Images',
        'description' => 'Kelola daftar gambar hero yang tampil pada landing page.',
        'searchable' => ['image_path', 'alt_text'],
        'with' => ['landingSetting'],
        'default_sort' => [
            ['column' => 'sort_order', 'direction' => 'asc'],
            ['column' => 'id', 'direction' => 'asc'],
        ],
        'table_columns' => [
            ['key' => 'landingSetting.site_name', 'label' => 'Landing Setting'],
            ['key' => 'image_path', 'label' => 'Image', 'type' => 'image'],
            ['key' => 'sort_order', 'label' => 'Order'],
            ['key' => 'is_active', 'label' => 'Active', 'type' => 'boolean'],
        ],
        'form_fields' => [
            ['name' => 'landing_setting_id', 'label' => 'Landing Setting', 'type' => 'select', 'required' => true, 'options_model' => LandingSetting::class, 'option_label' => 'site_name'],
            ['name' => 'image_path', 'label' => 'Image', 'type' => 'image', 'required' => true],
            ['name' => 'alt_text', 'label' => 'Alt Text', 'type' => 'text', 'hidden_from_form' => true],
            ['name' => 'sort_order', 'label' => 'Sort Order', 'type' => 'number', 'default' => 0],
            ['name' => 'is_active', 'label' => 'Active', 'type' => 'checkbox', 'default' => true, 'full_width' => true],
        ],
    ],
    'history' => [
        'label' => 'Histories',
        'navigation_label' => 'Histories',
        'navigation_group' => 'Landing Content',
        'navigation_icon' => 'calendar-days',
        'model' => History::class,
        'page_title' => 'Histories',
        'description' => 'Kelola arsip perjalanan festival dari tahun ke tahun, termasuk lokasi, kapasitas, tanggal acara, dan kumpulan gambar.',
        'searchable' => ['title', 'tahun', 'lokasi', 'content'],
        'with' => [],
        'default_sort' => [
            ['column' => 'order_by', 'direction' => 'asc'],
            ['column' => 'tahun', 'direction' => 'desc'],
        ],
        'table_columns' => [
            ['key' => 'thumbnail', 'label' => 'Thumbnail', 'type' => 'image'],
            ['key' => 'title', 'label' => 'Title', 'truncate' => 42],
            ['key' => 'tahun', 'label' => 'Tahun'],
            ['key' => 'lokasi', 'label' => 'Lokasi', 'truncate' => 32],
            ['key' => 'capacity', 'label' => 'Capacity'],
            ['key' => 'tanggal_acara', 'label' => 'Tanggal', 'type' => 'date'],
            ['key' => 'media', 'label' => 'Media', 'type' => 'count', 'suffix' => 'image'],
            ['key' => 'festival_galery', 'label' => 'Gallery', 'type' => 'count', 'suffix' => 'image'],
            ['key' => 'is_active', 'label' => 'Active', 'type' => 'boolean'],
        ],
        'form_fields' => [
            ['name' => 'order_by', 'label' => 'Order By', 'type' => 'number', 'default' => 0, 'hidden_from_form' => true],
            ['name' => 'title', 'label' => 'Title', 'type' => 'text', 'required' => true],
            ['name' => 'tahun', 'label' => 'Tahun', 'type' => 'number', 'required' => true, 'default' => 2026],
            ['name' => 'lokasi', 'label' => 'Lokasi', 'type' => 'text', 'required' => true],
            ['name' => 'capacity', 'label' => 'Capacity', 'type' => 'number', 'default' => 0],
            ['name' => 'tanggal_acara', 'label' => 'Tanggal Acara', 'type' => 'date'],
            ['name' => 'content', 'label' => 'Content', 'type' => 'rich_text', 'full_width' => true],
            ['name' => 'thumbnail', 'label' => 'Thumbnail', 'type' => 'image'],
            ['name' => 'media', 'label' => 'Media', 'type' => 'image_list', 'full_width' => true, 'max_kb' => 1024],
            ['name' => 'festival_galery', 'label' => 'Festival Gallery', 'type' => 'image_list', 'full_width' => true, 'max_kb' => 1024],
            ['name' => 'is_active', 'label' => 'Active', 'type' => 'checkbox', 'default' => true, 'full_width' => true],
        ],
    ],
    'lineup-artist' => [
        'label' => 'Lineup Artists',
        'navigation_label' => 'Lineup Artists',
        'navigation_group' => 'Landing Content',
        'navigation_icon' => 'microphone',
        'model' => LineupArtist::class,
        'page_title' => 'Lineup Artists',
        'description' => 'Kelola artis lineup, gambar, featured flag, dan urutan tampil.',
        'searchable' => ['name', 'alt_text', 'image_class'],
        'with' => [],
        'reorderable' => true,
        'reorder_field' => 'sort_order',
        'default_sort' => [
            ['column' => 'sort_order', 'direction' => 'asc'],
            ['column' => 'id', 'direction' => 'asc'],
        ],
        'table_columns' => [
            ['key' => 'name', 'label' => 'Artist'],
            ['key' => 'image_path', 'label' => 'Photo', 'type' => 'image'],
            ['key' => 'is_featured', 'label' => 'Featured', 'type' => 'boolean'],
            ['key' => 'sort_order', 'label' => 'Order'],
            ['key' => 'is_active', 'label' => 'Active', 'type' => 'boolean'],
        ],
        'form_fields' => [
            ['name' => 'name', 'label' => 'Artist Name', 'type' => 'text', 'required' => true],
            ['name' => 'image_path', 'label' => 'Image', 'type' => 'image'],
            ['name' => 'alt_text', 'label' => 'Alt Text', 'type' => 'text', 'hidden_from_form' => true],
            ['name' => 'image_class', 'label' => 'Image Class', 'type' => 'text'],
            ['name' => 'sort_order', 'label' => 'Sort Order', 'type' => 'number', 'default' => 0],
            ['name' => 'is_featured', 'label' => 'Featured', 'type' => 'checkbox', 'default' => false, 'full_width' => true],
            ['name' => 'is_active', 'label' => 'Active', 'type' => 'checkbox', 'default' => true, 'full_width' => true],
        ],
    ],
    'ticket' => [
        'label' => 'Tickets',
        'navigation_label' => 'Tickets',
        'navigation_group' => 'Landing Content',
        'navigation_icon' => 'ticket',
        'model' => Ticket::class,
        'page_title' => 'Tickets',
        'description' => 'Kelola batch tiket, harga, status penjualan, dan link pembelian.',
        'searchable' => ['name', 'batch_label', 'availability_label', 'status'],
        'with' => [],
        'reorderable' => true,
        'reorder_field' => 'sort_order',
        'default_sort' => [
            ['column' => 'sort_order', 'direction' => 'asc'],
            ['column' => 'id', 'direction' => 'asc'],
        ],
        'table_columns' => [
            ['key' => 'name', 'label' => 'Ticket'],
            ['key' => 'batch_label', 'label' => 'Batch'],
            ['key' => 'price', 'label' => 'Price', 'type' => 'money', 'currency_field' => 'currency'],
            ['key' => 'purchase_links', 'label' => 'Links', 'type' => 'count'],
            ['key' => 'sort_order', 'label' => 'Order'],
            ['key' => 'status', 'label' => 'Status', 'type' => 'badge'],
            ['key' => 'is_active', 'label' => 'Active', 'type' => 'boolean'],
        ],
        'form_fields' => [
            ['name' => 'name', 'label' => 'Ticket Name', 'type' => 'text', 'required' => true],
            ['name' => 'batch_label', 'label' => 'Batch Label', 'type' => 'text'],
            ['name' => 'price', 'label' => 'Price', 'type' => 'number', 'required' => true, 'default' => 0],
            ['name' => 'currency', 'label' => 'Currency', 'type' => 'select', 'required' => true, 'default' => 'IDR', 'options' => [
                ['value' => 'IDR', 'label' => 'IDR'],
                ['value' => 'USD', 'label' => 'USD'],
            ]],
            ['name' => 'status', 'label' => 'Status', 'type' => 'select', 'required' => true, 'default' => 'available', 'options' => [
                ['value' => 'available', 'label' => 'Available'],
                ['value' => 'limited', 'label' => 'Limited'],
                ['value' => 'sold_out', 'label' => 'Sold Out'],
                ['value' => 'coming_soon', 'label' => 'Coming Soon'],
            ]],
            [
                'name' => 'purchase_links',
                'label' => 'Purchase Links',
                'type' => 'link_list',
                'full_width' => true,
                'button_label' => 'Tambah Link',
                'item_label' => 'Link Pembelian',
                'url_placeholder' => 'https://example.com/tickets',
                'label_placeholder' => 'Contoh: Loket, Tiket.com, Batch 1',
                'allow_relative' => true,
                'sync_first_url_to' => 'purchase_url',
            ],
            ['name' => 'sort_order', 'label' => 'Sort Order', 'type' => 'number', 'default' => 0],
            ['name' => 'is_active', 'label' => 'Active', 'type' => 'checkbox', 'default' => true, 'full_width' => true],
        ],
    ],
    'ticket-card-element' => [
        'label' => 'Ticket Card Elements',
        'navigation_label' => 'Ticket Elements',
        'navigation_group' => 'Landing Content',
        'navigation_icon' => 'photo',
        'model' => TicketCardElement::class,
        'page_title' => 'Ticket Card Elements',
        'description' => 'Kelola gambar elemen dekoratif pada card ticket. Jika ada lebih dari satu elemen aktif, elemen akan diacak pada setiap card ticket.',
        'searchable' => ['name', 'alt_text'],
        'with' => [],
        'reorderable' => true,
        'reorder_field' => 'sort_order',
        'default_sort' => [
            ['column' => 'sort_order', 'direction' => 'asc'],
            ['column' => 'id', 'direction' => 'asc'],
        ],
        'table_columns' => [
            ['key' => 'image_path', 'label' => 'Element', 'type' => 'image'],
            ['key' => 'name', 'label' => 'Name'],
            ['key' => 'sort_order', 'label' => 'Order'],
            ['key' => 'is_active', 'label' => 'Active', 'type' => 'boolean'],
        ],
        'form_fields' => [
            ['name' => 'name', 'label' => 'Element Name', 'type' => 'text', 'required' => true],
            ['name' => 'image_path', 'label' => 'Element Image', 'type' => 'image', 'required' => true],
            ['name' => 'alt_text', 'label' => 'Alt Text', 'type' => 'text', 'hidden_from_form' => true],
            ['name' => 'sort_order', 'label' => 'Sort Order', 'type' => 'number', 'default' => 0],
            ['name' => 'is_active', 'label' => 'Active', 'type' => 'checkbox', 'default' => true, 'full_width' => true],
        ],
    ],
    'landing-body-element' => [
        'label' => 'Body Elements',
        'navigation_label' => 'Body Elements',
        'navigation_group' => 'Landing Content',
        'navigation_icon' => 'photo',
        'model' => LandingBodyElement::class,
        'page_title' => 'Body Elements',
        'description' => 'Kelola elemen dekoratif di sisi kanan dan kiri body landing per halaman/section. Maksimal 1MB per gambar.',
        'searchable' => ['title', 'page_section'],
        'with' => [],
        'default_sort' => [
            ['column' => 'page_section', 'direction' => 'asc'],
            ['column' => 'id', 'direction' => 'asc'],
        ],
        'table_columns' => [
            ['key' => 'id', 'label' => 'ID'],
            ['key' => 'image_path', 'label' => 'Image', 'type' => 'image'],
            ['key' => 'title', 'label' => 'Title'],
            ['key' => 'page_section', 'label' => 'Page Section', 'type' => 'badge'],
            ['key' => 'is_active', 'label' => 'Active', 'type' => 'boolean'],
        ],
        'form_fields' => [
            ['name' => 'title', 'label' => 'Title', 'type' => 'text', 'required' => true],
            ['name' => 'page_section', 'label' => 'Page Section', 'type' => 'select', 'required' => true, 'options' => [
                ['value' => 'lineup', 'label' => 'Lineup'],
                ['value' => 'ticket', 'label' => 'Ticket'],
                ['value' => 'merchandise', 'label' => 'Merchandise'],
                ['value' => 'gallery', 'label' => 'Gallery'],
                ['value' => 'rundown-map', 'label' => 'Rundown & Map'],
                ['value' => 'playlist', 'label' => 'Playlist'],
                ['value' => 'history', 'label' => 'History'],
                ['value' => 'sponsor-partner', 'label' => 'Sponsor & Partner'],
                ['value' => 'faq', 'label' => 'FAQ'],
                ['value' => 'contact', 'label' => 'Contact'],
                ['value' => 'about', 'label' => 'About'],
            ]],
            [
                'name' => 'image_path',
                'label' => 'Image',
                'type' => 'image',
                'required' => true,
                'max_kb' => 1024,
                'help_text' => 'Maksimal 1MB per gambar. Gunakan PNG/WebP transparan agar menyatu dengan background.',
            ],
            ['name' => 'is_active', 'label' => 'Active', 'type' => 'checkbox', 'default' => true, 'full_width' => true],
        ],
    ],
    'not-found-image' => [
        'label' => 'Not Found Images',
        'navigation_label' => 'Not Found Images',
        'navigation_group' => 'Landing Content',
        'navigation_icon' => 'photo',
        'model' => NotFoundImage::class,
        'page_title' => 'Not Found Images',
        'description' => 'Kelola gambar fallback/not found untuk setiap halaman atau section landing. Ukuran ideal image 1858px x 585px, maksimal 1MB per gambar.',
        'searchable' => ['title', 'page_section'],
        'with' => [],
        'default_sort' => [
            ['column' => 'page_section', 'direction' => 'asc'],
            ['column' => 'id', 'direction' => 'desc'],
        ],
        'table_columns' => [
            ['key' => 'id', 'label' => 'ID'],
            ['key' => 'image_path', 'label' => 'Image', 'type' => 'image'],
            ['key' => 'title', 'label' => 'Title'],
            ['key' => 'page_section', 'label' => 'Page Section', 'type' => 'badge'],
            ['key' => 'is_active', 'label' => 'Active', 'type' => 'boolean'],
        ],
        'form_fields' => [
            ['name' => 'title', 'label' => 'Title', 'type' => 'text', 'required' => true],
            ['name' => 'page_section', 'label' => 'Page Section', 'type' => 'select', 'required' => true, 'options' => [
                ['value' => 'home', 'label' => 'Home'],
                ['value' => 'hero', 'label' => 'Hero'],
                ['value' => 'lineup', 'label' => 'Lineup'],
                ['value' => 'ticket', 'label' => 'Ticket'],
                ['value' => 'merchandise', 'label' => 'Merchandise'],
                ['value' => 'gallery', 'label' => 'Gallery'],
                ['value' => 'rundown-map', 'label' => 'Rundown & Map'],
                ['value' => 'playlist', 'label' => 'Playlist'],
                ['value' => 'history', 'label' => 'History'],
                ['value' => 'sponsor-partner', 'label' => 'Sponsor & Partner'],
                ['value' => 'faq', 'label' => 'FAQ'],
                ['value' => 'contact', 'label' => 'Contact'],
                ['value' => 'about', 'label' => 'About'],
                ['value' => 'footer', 'label' => 'Footer'],
            ]],
            [
                'name' => 'image_path',
                'label' => 'Image',
                'type' => 'image',
                'required' => true,
                'max_kb' => 1024,
                'help_text' => 'Ukuran ideal 1858px x 585px. Maksimal 1MB per gambar.',
            ],
            ['name' => 'is_active', 'label' => 'Active', 'type' => 'checkbox', 'default' => true, 'full_width' => true],
        ],
    ],
    'spotify-playlist' => [
        'label' => 'Spotify Playlists',
        'navigation_label' => 'Spotify Playlists',
        'navigation_group' => 'Media & Partnership',
        'navigation_icon' => 'music-note',
        'model' => SpotifyPlaylist::class,
        'page_title' => 'Spotify Playlists',
        'description' => 'Kelola embed playlist Spotify yang tampil pada halaman Playlist.',
        'searchable' => ['label', 'title', 'embed_url', 'open_url'],
        'with' => [],
        'reorderable' => true,
        'reorder_field' => 'sort_order',
        'default_sort' => [
            ['column' => 'sort_order', 'direction' => 'asc'],
            ['column' => 'id', 'direction' => 'asc'],
        ],
        'table_columns' => [
            ['key' => 'label', 'label' => 'Label'],
            ['key' => 'title', 'label' => 'Title'],
            ['key' => 'embed_url', 'label' => 'Embed URL', 'truncate' => 70],
            ['key' => 'sort_order', 'label' => 'Order'],
            ['key' => 'is_active', 'label' => 'Active', 'type' => 'boolean'],
        ],
        'form_fields' => [
            ['name' => 'label', 'label' => 'Label', 'type' => 'text', 'required' => true, 'default' => 'Spotify'],
            ['name' => 'title', 'label' => 'Title', 'type' => 'text', 'required' => true, 'default' => 'Festival Warm Up'],
            ['name' => 'embed_url', 'label' => 'Embed URL / Iframe', 'type' => 'textarea', 'required' => true, 'full_width' => true],
            ['name' => 'open_url', 'label' => 'Open Spotify URL', 'type' => 'textarea', 'full_width' => true],
            ['name' => 'sort_order', 'label' => 'Sort Order', 'type' => 'number', 'default' => 0],
            ['name' => 'is_active', 'label' => 'Active', 'type' => 'checkbox', 'default' => true, 'full_width' => true],
        ],
    ],
    'merchandise-product' => [
        'label' => 'Merchandise Products',
        'navigation_label' => 'Products',
        'navigation_group' => 'Merchandise',
        'navigation_icon' => 'shopping-bag',
        'model' => MerchandiseProduct::class,
        'page_title' => 'Merchandise Products',
        'description' => 'Kelola produk merchandise utama beserta harga, thumbnail, kategori, dan order link.',
        'searchable' => ['name', 'slug', 'description'],
        'with' => ['images', 'category'],
        'default_sort' => [
            ['column' => 'sort_order', 'direction' => 'asc'],
            ['column' => 'id', 'direction' => 'asc'],
        ],
        'table_columns' => [
            ['key' => 'thumbnail_path', 'label' => 'Image', 'type' => 'image'],
            ['key' => 'name', 'label' => 'Product'],
            ['key' => 'category.name', 'label' => 'Category'],
            ['key' => 'slug', 'label' => 'Slug'],
            ['key' => 'price', 'label' => 'Price', 'type' => 'money', 'currency_field' => 'currency'],
            ['key' => 'discount_price', 'label' => 'Discount', 'type' => 'money', 'currency_field' => 'currency'],
            ['key' => 'stock_quantity', 'label' => 'Stock'],
            ['key' => 'is_active', 'label' => 'Active', 'type' => 'boolean'],
        ],
        'form_fields' => [
            ['name' => 'name', 'label' => 'Product Name', 'type' => 'text', 'required' => true],
            ['name' => 'slug', 'label' => 'Slug', 'type' => 'text', 'required' => true, 'unique' => true],
            ['name' => 'merchandise_product_category_id', 'label' => 'Category', 'type' => 'select', 'required' => true, 'options_model' => MerchandiseProductCategory::class, 'option_label' => 'name'],
            ['name' => 'price', 'label' => 'Price', 'type' => 'number', 'required' => true, 'default' => 0],
            ['name' => 'discount_price', 'label' => 'Discount Price', 'type' => 'number'],
            ['name' => 'currency', 'label' => 'Currency', 'type' => 'select', 'required' => true, 'default' => 'IDR', 'options' => [
                ['value' => 'IDR', 'label' => 'IDR'],
                ['value' => 'USD', 'label' => 'USD'],
            ]],
            ['name' => 'stock_quantity', 'label' => 'Stock Product', 'type' => 'number', 'default' => 0],
            ['name' => 'description', 'label' => 'Description', 'type' => 'rich_text', 'full_width' => true],
            ['name' => 'size_options', 'label' => 'Size Options', 'type' => 'option_list', 'full_width' => true, 'placeholder' => "S\nM\nL\nXL"],
            ['name' => 'color_options', 'label' => 'Color Options', 'type' => 'option_list', 'full_width' => true, 'placeholder' => "Hitam\nPutih\nCream"],
            ['name' => 'thumbnail_alt', 'label' => 'Thumbnail Alt', 'type' => 'text', 'hidden_from_form' => true],
            ['name' => 'thumbnail_class', 'label' => 'Thumbnail Class', 'type' => 'text', 'hidden_from_form' => true],
            [
                'name' => 'gallery_images',
                'label' => 'Gallery Images',
                'type' => 'image_gallery',
                'full_width' => true,
                'relation' => 'images',
                'item_model' => MerchandiseProductImage::class,
                'item_alt_field' => 'alt_text',
                'item_path_field' => 'image_path',
                'item_class_field' => 'image_class',
                'item_sort_field' => 'sort_order',
                'item_active_field' => 'is_active',
                'default_class' => 'object-cover',
                'auto_fill_thumbnail' => true,
            ],
            ['name' => 'sort_order', 'label' => 'Sort Order', 'type' => 'number', 'default' => 0],
            ['name' => 'is_active', 'label' => 'Active', 'type' => 'checkbox', 'default' => true, 'full_width' => true],
        ],
    ],
    'merchandise-product-category' => [
        'label' => 'Merchandise Categories',
        'navigation_label' => 'Categories',
        'navigation_group' => 'Merchandise',
        'navigation_icon' => 'tag',
        'model' => MerchandiseProductCategory::class,
        'page_title' => 'Merchandise Categories',
        'description' => 'Kelola kategori untuk produk merchandise.',
        'searchable' => ['name', 'slug', 'description'],
        'auto_slug_from_name' => true,
        'default_sort' => [
            ['column' => 'sort_order', 'direction' => 'asc'],
            ['column' => 'name', 'direction' => 'asc'],
        ],
        'reorderable' => true,
        'reorder_field' => 'sort_order',
        'table_columns' => [
            ['key' => 'name', 'label' => 'Category'],
            ['key' => 'slug', 'label' => 'Slug'],
            ['key' => 'sort_order', 'label' => 'Order'],
            ['key' => 'is_active', 'label' => 'Active', 'type' => 'boolean'],
        ],
        'form_fields' => [
            ['name' => 'name', 'label' => 'Category Name', 'type' => 'text', 'required' => true],
            ['name' => 'slug', 'label' => 'Slug', 'type' => 'text', 'required' => true, 'unique' => true],
            ['name' => 'description', 'label' => 'Description', 'type' => 'textarea', 'full_width' => true],
            ['name' => 'sort_order', 'label' => 'Sort Order', 'type' => 'number', 'default' => 0],
            ['name' => 'is_active', 'label' => 'Active', 'type' => 'checkbox', 'default' => true, 'full_width' => true],
        ],
    ],
    'product-image' => [
        'hidden' => true,
        'label' => 'Product Images',
        'navigation_label' => 'Product Images',
        'navigation_group' => 'Merchandise',
        'navigation_icon' => 'rectangle-stack',
        'model' => MerchandiseProductImage::class,
        'page_title' => 'Product Images',
        'description' => 'Kelola gambar tambahan untuk tiap produk merchandise.',
        'searchable' => ['image_path', 'alt_text', 'image_class'],
        'with' => ['product'],
        'default_sort' => [
            ['column' => 'sort_order', 'direction' => 'asc'],
            ['column' => 'id', 'direction' => 'asc'],
        ],
        'table_columns' => [
            ['key' => 'product.name', 'label' => 'Product'],
            ['key' => 'image_path', 'label' => 'Image', 'type' => 'image'],
            ['key' => 'sort_order', 'label' => 'Order'],
            ['key' => 'is_active', 'label' => 'Active', 'type' => 'boolean'],
        ],
        'form_fields' => [
            ['name' => 'merchandise_product_id', 'label' => 'Product', 'type' => 'select', 'required' => true, 'options_model' => MerchandiseProduct::class, 'option_label' => 'name'],
            ['name' => 'image_path', 'label' => 'Image', 'type' => 'image', 'required' => true],
            ['name' => 'alt_text', 'label' => 'Alt Text', 'type' => 'text', 'hidden_from_form' => true],
            ['name' => 'image_class', 'label' => 'Image Class', 'type' => 'text'],
            ['name' => 'sort_order', 'label' => 'Sort Order', 'type' => 'number', 'default' => 0],
            ['name' => 'is_active', 'label' => 'Active', 'type' => 'checkbox', 'default' => true, 'full_width' => true],
        ],
    ],
    'gallery-moment' => [
        'label' => 'Gallery Moments',
        'navigation_label' => 'Gallery Moments',
        'navigation_group' => 'Media & Partnership',
        'navigation_icon' => 'camera',
        'model' => GalleryMoment::class,
        'page_title' => 'Gallery Moments',
        'description' => 'Kelola konten gallery, username, deskripsi, gambar, dan urutan tampil.',
        'searchable' => ['title', 'username', 'description', 'alt_text'],
        'with' => [],
        'default_sort' => [
            ['column' => 'sort_order', 'direction' => 'asc'],
            ['column' => 'id', 'direction' => 'asc'],
        ],
        'table_columns' => [
            ['key' => 'image_path', 'label' => 'Image', 'type' => 'image'],
            ['key' => 'title', 'label' => 'Title'],
            ['key' => 'username', 'label' => 'Username'],
            ['key' => 'description', 'label' => 'Description', 'truncate' => 60],
            ['key' => 'sort_order', 'label' => 'Order'],
            ['key' => 'is_active', 'label' => 'Active', 'type' => 'boolean'],
        ],
        'form_fields' => [
            ['name' => 'title', 'label' => 'Title', 'type' => 'text', 'required' => true],
            ['name' => 'username', 'label' => 'Username', 'type' => 'text'],
            ['name' => 'description', 'label' => 'Description', 'type' => 'textarea', 'full_width' => true],
            ['name' => 'image_path', 'label' => 'Image', 'type' => 'image'],
            ['name' => 'alt_text', 'label' => 'Alt Text', 'type' => 'text', 'hidden_from_form' => true],
            ['name' => 'sort_order', 'label' => 'Sort Order', 'type' => 'number', 'default' => 0],
            ['name' => 'is_active', 'label' => 'Active', 'type' => 'checkbox', 'default' => true, 'full_width' => true],
        ],
    ],
    'sponsor-partner' => [
        'label' => 'Sponsor Partners',
        'navigation_label' => 'Sponsor Partners',
        'navigation_group' => 'Media & Partnership',
        'navigation_icon' => 'building-storefront',
        'model' => SponsorPartner::class,
        'page_title' => 'Sponsor Partners',
        'description' => 'Kelola sponsor, partner, tier, logo, url, dan deskripsi.',
        'searchable' => ['name', 'tier', 'description'],
        'with' => [],
        'reorderable' => true,
        'reorder_field' => 'sort_order',
        'default_sort' => [
            ['column' => 'sort_order', 'direction' => 'asc'],
            ['column' => 'id', 'direction' => 'asc'],
        ],
        'table_columns' => [
            ['key' => 'logo_path', 'label' => 'Logo', 'type' => 'image'],
            ['key' => 'name', 'label' => 'Partner'],
            ['key' => 'tier', 'label' => 'Tier', 'type' => 'badge'],
            ['key' => 'sort_order', 'label' => 'Order'],
            ['key' => 'is_active', 'label' => 'Active', 'type' => 'boolean'],
        ],
        'form_fields' => [
            ['name' => 'name', 'label' => 'Partner Name', 'type' => 'text', 'required' => true],
            ['name' => 'tier', 'label' => 'Tier', 'type' => 'text'],
            ['name' => 'logo_path', 'label' => 'Logo', 'type' => 'image'],
            ['name' => 'url', 'label' => 'URL', 'type' => 'url'],
            ['name' => 'description', 'label' => 'Description', 'type' => 'textarea', 'full_width' => true],
            ['name' => 'sort_order', 'label' => 'Sort Order', 'type' => 'number', 'default' => 0],
            ['name' => 'is_active', 'label' => 'Active', 'type' => 'checkbox', 'default' => true, 'full_width' => true],
        ],
    ],
    'contact-channel' => [
        'label' => 'Contact Channels',
        'navigation_label' => 'Contact Channels',
        'navigation_group' => 'Media & Partnership',
        'navigation_icon' => 'chat-bubble-left-right',
        'model' => ContactChannel::class,
        'page_title' => 'Contact Channels',
        'description' => 'Kelola kanal kontak yang ditampilkan di halaman contact atau footer.',
        'searchable' => ['label', 'icon', 'type', 'value', 'description'],
        'with' => [],
        'default_sort' => [
            ['column' => 'sort_order', 'direction' => 'asc'],
            ['column' => 'id', 'direction' => 'asc'],
        ],
        'table_columns' => [
            ['key' => 'icon', 'label' => 'Icon', 'type' => 'contact_icon'],
            ['key' => 'label', 'label' => 'Label'],
            ['key' => 'type', 'label' => 'Type', 'type' => 'badge'],
            ['key' => 'value', 'label' => 'Value', 'truncate' => 35],
            ['key' => 'sort_order', 'label' => 'Order'],
            ['key' => 'is_active', 'label' => 'Active', 'type' => 'boolean'],
        ],
        'form_fields' => [
            ['name' => 'label', 'label' => 'Label', 'type' => 'text', 'required' => true],
            ['name' => 'icon', 'label' => 'Icon', 'type' => 'select', 'default' => 'email', 'options' => [
                ['value' => 'whatsapp', 'label' => 'WhatsApp / Phone'],
                ['value' => 'email', 'label' => 'Email'],
                ['value' => 'instagram', 'label' => 'Instagram'],
                ['value' => 'tiktok', 'label' => 'TikTok'],
                ['value' => 'website', 'label' => 'Website'],
                ['value' => 'chat-bubble', 'label' => 'Chat Bubble'],
            ]],
            ['name' => 'type', 'label' => 'Type', 'type' => 'select', 'required' => true, 'default' => 'email', 'options' => [
                ['value' => 'email', 'label' => 'Email'],
                ['value' => 'phone', 'label' => 'Phone'],
                ['value' => 'whatsapp', 'label' => 'WhatsApp'],
                ['value' => 'instagram', 'label' => 'Instagram'],
                ['value' => 'tiktok', 'label' => 'TikTok'],
                ['value' => 'website', 'label' => 'Website'],
            ]],
            ['name' => 'value', 'label' => 'Value', 'type' => 'text'],
            ['name' => 'url', 'label' => 'URL', 'type' => 'url'],
            ['name' => 'description', 'label' => 'Description', 'type' => 'textarea', 'full_width' => true],
            ['name' => 'sort_order', 'label' => 'Sort Order', 'type' => 'number', 'default' => 0],
            ['name' => 'is_active', 'label' => 'Active', 'type' => 'checkbox', 'default' => true, 'full_width' => true],
        ],
    ],
    'frequently-asked-question' => [
        'label' => 'FAQ',
        'navigation_label' => 'FAQ',
        'navigation_group' => 'Landing Content',
        'navigation_icon' => 'question-mark-circle',
        'model' => FrequentlyAskedQuestion::class,
        'page_title' => 'FAQ',
        'description' => 'Kelola daftar pertanyaan dan jawaban yang tampil pada halaman FAQ.',
        'searchable' => ['question', 'answer'],
        'with' => [],
        'reorderable' => true,
        'reorder_field' => 'sort_order',
        'default_sort' => [
            ['column' => 'sort_order', 'direction' => 'asc'],
            ['column' => 'id', 'direction' => 'asc'],
        ],
        'table_columns' => [
            ['key' => 'question', 'label' => 'Question', 'truncate' => 55],
            ['key' => 'answer', 'label' => 'Answer', 'truncate' => 80],
            ['key' => 'sort_order', 'label' => 'Order'],
            ['key' => 'is_active', 'label' => 'Active', 'type' => 'boolean'],
        ],
        'form_fields' => [
            ['name' => 'question', 'label' => 'Question', 'type' => 'text', 'required' => true],
            ['name' => 'answer', 'label' => 'Answer', 'type' => 'textarea', 'required' => true, 'full_width' => true],
            ['name' => 'sort_order', 'label' => 'Sort Order', 'type' => 'number', 'default' => 0],
            ['name' => 'is_active', 'label' => 'Active', 'type' => 'checkbox', 'default' => true, 'full_width' => true],
        ],
    ],
];
